name: Deploy to GCE VM (WIF Secure)

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment"
        required: true
        default: "dev"
        options:
          - dev
          - stage
          - prod
      app:
        type: string
        description: "App folder"
        default: "app1"
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate with WIF
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Configure gcloud
        run: |
          gcloud config set project kxnwork

      - name: Build artifact
        run: |
          APP="${{ github.event.inputs.app }}"
          mkdir -p dist
          tar -czf dist/${APP}.tar.gz ${APP}

      - name: Upload to VM (IAP)
        run: |
          APP="${{ github.event.inputs.app }}"
          VM="${{ secrets.TARGET_VM_NAME }}"
          ZONE="${{ secrets.TARGET_VM_ZONE }}"
          USER="${{ secrets.TARGET_VM_USER }}"
          gcloud compute scp \
            dist/${APP}.tar.gz \
            ${USER}@${VM}:/tmp/${APP}.tar.gz \
            --zone="${ZONE}" --tunnel-through-iap

      - name: Execute remote deploy
        run: |
          APP="${{ github.event.inputs.app }}"
          VM="${{ secrets.TARGET_VM_NAME }}"
          USER="${{ secrets.TARGET_VM_USER }}"
          ZONE="${{ secrets.TARGET_VM_ZONE }}"

          CMD="mkdir -p /opt/apps/${APP} && \
               tar -xzf /tmp/${APP}.tar.gz -C /opt/apps/${APP} && \
               echo 'Deployed ${APP}'"

          gcloud compute ssh ${USER}@${VM} \
            --zone=${ZONE} --tunnel-through-iap \
            --command=\"${CMD}\"
